server:
  port: 8088
spring:
  task:
    execution:
      pool:
        core-size: 3
        max-size: 5
        queue-capacity: 10
        keep-alive: 60s
        allow-core-thread-timeout: true
      thread-name-prefix: task-run
logging:
  config: classpath:log4j2.xml

